esphome:
  name: heizung
  friendly_name: Heizung

esp32:
  board: esp32dev
  framework:
    type: esp-idf

# Enable logging
logger:
  level: DEBUG
  logs:
    component: ERROR
    mqtt: INFO
    modbus: ERROR
    modbus.number: INFO
    modbus_controller: INFO
    modbus_controller.sensor: INFO
    internal_temperature: INFO
    sensor: INFO
    number: INFO
    switch: DEBUG
    binary_sensor: INFO
    web_server_idf: ERROR
    #switch: INFO
  #level: DEBUG
  baud_rate: 0  # Disable UART logging

# Enable Home Assistant API
# Cannot be used together with MQTT!!!
api:
  reboot_timeout: 0s
  encryption:
    key: !secret encryption

ota:
  - platform: esphome
    password: !secret ota_password

mqtt:
  broker: !secret mqtt_broker
  port: !secret mqtt_port
  username: !secret mqtt_username
  password: !secret mqtt_password  
  on_connect:
    then:
    - mqtt.publish:
        topic: "switch/heizung_on_off/command"
        payload: "NA"      

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Heizung2 Fallback Hotspot"
    password: !secret wifi_ap_password
captive_portal:

web_server:
  port: 80
  auth:
    username: !secret web_server_username
    password: !secret web_server_password

uart:
  - id: modbus_uart2
    tx_pin: GPIO17
    rx_pin: GPIO16
    baud_rate: 9600
    parity: NONE
    stop_bits: 1
    data_bits: 8
    #debug:
    #  direction: BOTH
#  - id: modbus_uart1
#    tx_pin: GPIO01
#    rx_pin: GPIO03
#    baud_rate: 9600
#    parity: NONE
#    stop_bits: 1
#    data_bits: 8
#    debug:
#      direction: BOTH
   

modbus:
  - id: modbus_client
    uart_id: modbus_uart2
    role: client
    send_wait_time: 100ms
#  - id: modbus_server
#    uart_id: modbus_uart2
#    role: server
#    send_wait_time: 500ms



modbus_controller:
  - id: modbus_master
    modbus_id: modbus_client
    address: 0x01
    command_throttle: 50ms
    update_interval: 5s
    max_cmd_retries: 0
#  - id: modbus_slave
#    modbus_id: modbus_server
#    address: 0x2
#    server_registers:
#      - address: 0x1234
#        value_type: U_DWORD_R
#        discrete_input_lambda: return 5;


binary_sensor:
- platform: modbus_controller
  modbus_controller_id: modbus_master
  name: "Durchflussrate not OK"
  register_type: discrete_input
  address: 0
#  bitmask: 0x1
- platform: modbus_controller
  modbus_controller_id: modbus_master
  name: "Wasserpumpe Status"
  register_type: discrete_input
  address: 1
#  bitmask: 0x1
- platform: modbus_controller
  modbus_controller_id: modbus_master
  name: "Wasserpumpe Ext. Status"
  register_type: discrete_input
  address: 2
#  bitmask: 0x1
- platform: modbus_controller
  modbus_controller_id: modbus_master
  name: "Kompressor Status"
  register_type: discrete_input
  address: 3
  bitmask: 0x1
- platform: modbus_controller
  modbus_controller_id: modbus_master
  name: "Abtaustatus"
  register_type: discrete_input
  address: 4
  bitmask: 0x1
- platform: modbus_controller
  modbus_controller_id: modbus_master
  name: "DHW Heizstab"
  register_type: discrete_input
  address: 5
  bitmask: 0x1
- platform: modbus_controller
  modbus_controller_id: modbus_master
  name: "Desinfektionsstatus"
  register_type: discrete_input
  address: 6
  bitmask: 0x1
- platform: modbus_controller
  modbus_controller_id: modbus_master
  name: "SilentMode"
  register_type: discrete_input
  address: 7
  bitmask: 0x1
- platform: modbus_controller
  modbus_controller_id: modbus_master
  name: "Kühlstatus"
  register_type: discrete_input
  address: 8
  bitmask: 0x1
- platform: modbus_controller
  modbus_controller_id: modbus_master
  name: "Solarpumpe"
  register_type: discrete_input
  address: 9
  bitmask: 0x1
- platform: modbus_controller
  modbus_controller_id: modbus_master
  name: "Zusatzheizung Step 1"
  register_type: discrete_input
  address: 10
  bitmask: 0x1
- platform: modbus_controller
  modbus_controller_id: modbus_master
  name: "Zusatzheizung Step 2"
  register_type: discrete_input
  address: 11
  bitmask: 0x1
- platform: modbus_controller
  modbus_controller_id: modbus_master
  name: "DHW Booster Heizstab"
  register_type: discrete_input
  address: 12
  bitmask: 0x1
- platform: modbus_controller
  modbus_controller_id: modbus_master
  name: "Fehlermeldung"
  register_type: discrete_input
  address: 13
  bitmask: 0x1
- platform: modbus_controller
  modbus_controller_id: modbus_master
  name: "Notbetrieb Raumheizung verfügbar"
  register_type: discrete_input
  address: 14
  bitmask: 0x1
- platform: modbus_controller
  modbus_controller_id: modbus_master
  name: "Notbetrieb DHW verfügbar"
  register_type: discrete_input
  address: 15
  bitmask: 0x1
- platform: modbus_controller
  modbus_controller_id: modbus_master
  name: "Status Mischpumpe"
  register_type: discrete_input
  address: 16 
  bitmask: 0x1

sensor:
- platform: uptime
  name: "Uptime"
  update_interval: 10s
- platform: wifi_signal
  name: "WiFi Signal Sensor"
  update_interval: 1s
  filters:
  - median:
      window_size: 10
      send_every: 10
- platform: internal_temperature
  name: "Internal Temperature"
  update_interval: 1s
  filters:
  - median:
      window_size: 10
      send_every: 10 
- platform: modbus_controller
  modbus_controller_id: modbus_master
  name: "Errorcode"
  register_type: read
  address: 0
  value_type: S_WORD
- platform: modbus_controller
  modbus_controller_id: modbus_master
  name: "CDU OperationMode"
  register_type: read
  address: 1
  value_type: S_WORD
- platform: modbus_controller
  modbus_controller_id: modbus_master
  name: "Wassereinlasstemperatur"
  register_type: read
  address: 2
  value_type: S_WORD
  filters:
    - multiply: 0.1  
- platform: modbus_controller
  modbus_controller_id: modbus_master
  name: "Wasserauslasstemperatur"
  register_type: read
  address: 3
  value_type: S_WORD
  filters:
    - multiply: 0.1  
- platform: modbus_controller
  modbus_controller_id: modbus_master
  name: "Auslasstemperatur Backupheater"
  register_type: read
  address: 4
  value_type: S_WORD
  filters:
    - multiply: 0.1  
- platform: modbus_controller
  modbus_controller_id: modbus_master
  name: "Temperatur DHW"
  register_type: read
  address: 5
  value_type: S_WORD
  filters:
    - multiply: 0.1  
- platform: modbus_controller
  modbus_controller_id: modbus_master
  name: "Temperatur Sonnenkollektor"
  register_type: read
  address: 6
  value_type: S_WORD
  filters:
    - multiply: 0.1  
- platform: modbus_controller
  modbus_controller_id: modbus_master
  name: "Raumlufttemperatur Circuit1"
  register_type: read
  address: 7
  value_type: S_WORD
  filters:
    - multiply: 0.1  
- platform: modbus_controller
  modbus_controller_id: modbus_master
  name: "Durchflussrate"
  register_type: read
  address: 8
  value_type: S_WORD
  filters:
    - multiply: 0.1
- platform: modbus_controller
  modbus_controller_id: modbus_master
  name: "Durchflusstemperatur Circuit2"
  register_type: read
  address: 9
  value_type: S_WORD
  filters:
    - multiply: 0.1      
- platform: modbus_controller
  modbus_controller_id: modbus_master
  name: "Raumlufttemperatur Circuit2"
  register_type: read
  address: 10
  value_type: S_WORD 
- platform: modbus_controller
  modbus_controller_id: modbus_master
  name: "Energiezustand"
  register_type: read
  address: 11
  value_type: S_WORD
- platform: modbus_controller
  modbus_controller_id: modbus_master
  name: "Temperatur Außen"
  register_type: read
  address: 12
  value_type: S_WORD
  filters:
    - multiply: 0.1  
- platform: modbus_controller
  modbus_controller_id: modbus_master
  name: "Temperatur Flüssiggas"
  register_type: read
  address: 16
  value_type: S_WORD
  filters:
      - multiply: 0.1  
- platform: modbus_controller
  modbus_controller_id: modbus_master
  name: "Temperatur Absaugung"
  register_type: read
  address: 18
  value_type: S_WORD
  filters:
    - multiply: 0.1  
- platform: modbus_controller
  modbus_controller_id: modbus_master
  name: "Heißgastemperatur"
  register_type: read
  address: 19
  value_type: S_WORD
  filters:
    - multiply: 0.1  
- platform: modbus_controller
  modbus_controller_id: modbus_master
  name: "Dampftemperatut vor VErdampfer"
  register_type: read
  address: 20
  value_type: S_WORD
  filters:
    - multiply: 0.1  
- platform: modbus_controller
  modbus_controller_id: modbus_master
  name: "Dampftemperatur nach Verdampfer"
  register_type: read
  address: 21
  value_type: S_WORD
  filters:
    - multiply: 0.1  
- platform: modbus_controller
  modbus_controller_id: modbus_master
  name: "Dampfdurck Kondensator"
  register_type: read
  address: 22
  value_type: S_WORD
  filters:
    - multiply: 0.1  
- platform: modbus_controller
  modbus_controller_id: modbus_master
  name: "Dampfdruck Kondensator"
  register_type: read
  address: 23
  value_type: S_WORD
  filters:
    - multiply: 0.1  
- platform: modbus_controller
  modbus_controller_id: modbus_master
  name: "Kompressordrehzahl"
  register_type: read
  address: 24
  value_type: S_WORD
#  filters:
#    - multiply: 0.1

number:
- name: "OperationMode"
  register_type: holding
  address: 0
  platform: modbus_controller
  modbus_controller_id: modbus_master
  value_type: S_WORD
  min_value: 0
  max_value: 4
  step: 1
  multiply: 1.0
- name: "ControlMethod"
  register_type: holding
  value_type: S_WORD
  address: 1
  min_value: 0
  max_value: 1
  step: 1
  multiply: 1.0
  platform: modbus_controller
  modbus_controller_id: modbus_master
- name: "Circuit1.TargetTemp"
  register_type: holding
  value_type: S_WORD
  address: 2
  min_value: 30
  max_value: 55
  step: 1.0
  multiply: 10.0
  platform: modbus_controller
  modbus_controller_id: modbus_master
- name: "Circuit1.AirTemp"
  register_type: holding
  value_type: S_WORD
  address: 3
  min_value: 20
  max_value: 30
  step: 1.0
  multiply: 10.0
  platform: modbus_controller
  modbus_controller_id: modbus_master
- name: "Circuit1.TempShift"
  register_type: holding
  value_type: S_WORD
  address: 4
  min_value: -3
  max_value: 3
  step: 1
  multiply: 1
  platform: modbus_controller
  modbus_controller_id: modbus_master
- name: "Circuit2.TargetTemp"
  register_type: holding
  value_type: S_WORD
  address: 5
  min_value: 30
  max_value: 50
  step: 1.0
  multiply: 10.0
  platform: modbus_controller
  modbus_controller_id: modbus_master
- name: "Circuit2.AirTemp"
  register_type: holding
  value_type: S_WORD
  address: 6
  min_value: 20
  max_value: 30
  step: 1.0
  multiply: 10.0
  platform: modbus_controller
  modbus_controller_id: modbus_master
- name: "Circuit2.TempShift"
  register_type: holding
  value_type: S_WORD
  address: 7
  min_value: -3
  max_value: 3
  step: 1
  multiply: 1
  platform: modbus_controller
  modbus_controller_id: modbus_master
- name: "DHWTargetTemp"
  register_type: holding
  value_type: S_WORD
  address: 8
  min_value: 30
  max_value: 58
  step: 1
  multiply: 10
  platform: modbus_controller
  modbus_controller_id: modbus_master
- name: "EnergyState"
  register_type: holding
  value_type: S_WORD
  address: 9
  min_value: 0
  max_value: 10
  step: 1
  multiply: 1
  platform: modbus_controller
  modbus_controller_id: modbus_master

switch:
- platform: restart
  name: "Restart"
- platform: modbus_controller
  modbus_controller_id: modbus_master
  name: "Heizung On/Off"
  register_type: coil
  address: 0
- platform: modbus_controller
  modbus_controller_id: modbus_master
  name: "DHW On/Off"
  register_type: coil
  address: 1
- platform: modbus_controller
  modbus_controller_id: modbus_master
  name: "SlientModus"
  register_type: coil
  address: 2 
- platform: modbus_controller
  modbus_controller_id: modbus_master
  name: "Desinfektion"
  register_type: coil
  address: 3
- platform: modbus_controller
  modbus_controller_id: modbus_master
  name: "KompressorStop"
  register_type: coil
  address: 4
- platform: modbus_controller
  modbus_controller_id: modbus_master
  name: "KompressorStart"
  register_type: coil
  address: 5 
